# Generated by Django 3.0.5 on 2022-02-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
    ]
