# Generated by Django 3.0.5 on 2022-02-07 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220207_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='update_at',
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado el'),
            preserve_default=False,
        ),
    ]
