# Generated by Django 3.0.5 on 2022-02-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220207_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='fecha',
            new_name='created_at',
        ),
    ]
