# Generated by Django 3.0.5 on 2022-02-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220207_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Creado el'),
        ),
    ]
