# Generated by Django 3.0.5 on 2022-02-07 23:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_receta_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(default='null', upload_to='recetas', verbose_name='Imagen de presentacion'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima actualizacion'),
        ),
    ]
