# Generated by Django 3.0.5 on 2022-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220207_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='difficult',
            field=models.CharField(blank=True, choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'IT')], max_length=1, null=True, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='public',
            field=models.BooleanField(default=True, verbose_name='¿Visible?'),
        ),
    ]
